on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    steps:
      - uses: actions/checkout@v2 
      - run: |
             apt update -y
             apt install cmake -y
             apt install -y cppcheck clang-tidy python3-pip libc6-dbg cmake libgtest-dev
             make check
      - run: |
             wget https://sourceware.org/pub/valgrind/valgrind-3.18.1.tar.bz2 && \
             tar xfv valgrind-3.18.1.tar.bz2 && \
             cd valgrind-3.18.1 && \
             ./autogen.sh && \
             ./configure && \
             make && \
             make install
      - run: |
             make build
             make test
